---
title: "Course Project"
author: 
  - name: Eleana Cabello
    affiliation: Department of Microbiology and Immunology, OUHS
date: 2025-7-18
draft: True
--- 
# Background

The goal of the course project is to get you practicing with real life data you are encountering in your research. Therefore, we are letting you decide what data you want to work with for this project.

Below is table of important dates and what is needed by those days:

### Timeline and Deliverables
```{=html}
<table style="width:100%">
    <tr>
    <th style="width:20%">07/15/25</th>
    <th style="width:40%">Summary of Project</th>
    <th style="width:40%">Brief paragraph on the data set you will be using for the project including goals of the analysis</th>
    </tr>
    <tr>
    <td>07/22/25</td>
    <td>Project Work Day</td>
    <td>Get help from instructors on any tasks you may be stuck on</td>
    </tr>
    <tr>
    <td>07/24/25 07/28/25</td>
    <td>Presentations </td>
    <td>10-15 min limit</td>
    </tr>
</table>
```


# Submission

Project submission will be done through your Github website we have previously created. Have your project file (.qmd file) in your website directory. However you would like to accomplish this: copying file into the directory, creating a new file and copying text over into the new file, or creating new qmd file in the directory and redoing your project) it does not matter what method is used. What matters is you push the new file changes (your new project file) to your Github repository, where these changes will be changed to HTML files and displayed on your website. 

Afterwards, fill the following form to submit your project: [Project Google Form Submission](https://docs.google.com/forms/d/e/1FAIpQLScslu7SP6AF9CqL6q2oCCJ7sUUdYsbYFx3eXNojCArgYRnKnQ/viewform?usp=header)

### Rubric
```{=html}
<table border="0">
  <thead>
  </thead>
  <tbody>
    <tr>
    <th style="width:20%"></th>
    <th style="width:40%">Did the final project have a clearly stated analysis goal?</th>
    <th style="width:40%">Did the final project successfully achieve that goal?</th>
    </tr>
    <tr>
    <td>5pts (Good)</td>
    <td>Student understood the assignment, picked a task that could be completed by data science, and clearly communicated the problem and goals.</td>
    <td>The student was able to write a script to address their problem and present the problem, logic and organization of the script, and achieved the stated goals.</td>
    </tr>
    <tr>
    <td>3pts (Fair)</td>
    <td>The student attempted the assignment, identified a problem, and was able to partially communicate the goals of the project.</td>
    <td>The student was able to communicate the problem, attempted a script to achieve the goal, but was only partially able to achieve the stated goals.</td>
    </tr>
    <tr>
    <td>1pt (Poor)</td>
    <td>The student did not understand the assignment, was not able to communicate a problem or identify achievable goals.</td>
    <td>The student poorly communicated the problem, did not find a logical solution, and was not able to achieve the stated goals.</td>
    </tr>
  </tbody>
</table>
```
