---
title: "Welcome to the Course!"
author: 
  - name: Lindsay Hayes
    url: https://lindsaynhayes.github.io
    affiliation: Department of Cell Biology, OUHSC
description: "Getting Ready for Your First Day!"
date: 2025-07-01
---

# Pre-lecture activities

The course will *exclusively* use R in the integrated development environment (IDE) called R Studio. Since the summer semester is only 1 month (10 classes), it is **critical to have your computer set up and ready to go before the first day of class**.

Throughout the course, there will be a set of pre-lecture activities and/or readings for you to complete. **These activities prepare you for the in-class activities**. Failure to complete them will put you behind in an already compressed course.

To prepare for the first class:

1.  Install R and R Studio
    -   [installation video tutorial](https://www.youtube.com/watch?v=eQFu_zzF96o)
    -   Detailed instructions on installing R and R Studio are available on [swirl](https://swirlstats.com/students.html).
        -   Complete step 1 and step 2

::: callout-tip

Swirl is a great tool to learn R interactively that we will use in the course. Feel free to explore more.
:::

2. In the first class, we will begin to get familiar with R. Complete the [Pre-reading material about R](./../readings/index_R01.qmd). Pre-reading materials for each class are located under **Resources**. Sometimes, pre-reading materials are direct links to external resources for you to read in advance of the lecture.


# Lecture

## Learning objectives

::: callout-note
### Learning objectives

**At the end of this lesson you will:**

-   Get an overview of the course (including staff, format, grading, etc)
-   Be able to recognize and operate an Integrated Developer Environment (IDE). 
-   Be able to recognize a Quarto document and describe reasons why to use a unified authoring framework.
-   Be able to create a R project & Quarto document.

:::

## Slides 

- [Lecture 01: Welcome and Introductions](https://docs.google.com/presentation/d/12EGF_lMFltLHzngleEi6jxZ3phncEhTl5vm05-y_cLI/edit?usp=sharing)

## Acknowledgements

Material for this lecture was borrowed and adopted from

-   sw carpentry: <https://carpentries-incubator.github.io/bioc-intro/20-r-rstudio.html>
-   data carpentry: <https://datacarpentry.github.io/genomics-r-intro/00-introduction.html>


# Post-lecture Practice

## Summary 

- Access all course material on CoursePlus and course website (<https://www.stephaniehicks.com/jhustatprogramming2024>)
- Lectures will be recorded followed by an in-class activity. Later in the course, the in-class activity will be to work on the final project
- At the end of each class, fill out the [reflection card](https://forms.gle/YE9kpBf7aVnx8VMdA) (not graded, but helpful to both the student and instructor)
- Integrated developer environment (IDEs) can make you more efficient as a programmer! 
- Quarto is an open-source scientific and technical publishing system to create reproducible, production quality articles, presentations, dashboards, websites, blogs, and books in HTML, PDF, MS Word, and more
- You can think of Quarto as a natural successor to RMarkdown

## Additional practice

Here are some additional practice questions to help you think about the material discussed.

::: callout-note
### Questions

1.  In either RStudio or VSCode, create a new Quarto document. Read the instructions. Practice running the chunks individually. Then render the document and practice the appropriate keyboard short cut. Verify that you can modify the code, re-run it, and see modified output.

2.  Create one new Quarto document for each of the three built-in formats: HTML, PDF and Word. Render each of the three documents. How do the outputs differ? How do the inputs differ? (You may need to install LaTeX in order to build the PDF output --- RStudio will prompt you if this is necessary.)

:::
