---
title: "Welcome to the course"
author: 
  - name: Lindsay Hayes
    url: https://lindsaynhayes.github.io
    affiliation: Department of Cell Biology, OUHSC
description: "Getting Ready for Your First Day!"
date: today
---

# Pre-lecture activities

The course will *exclusively* use R in the integrated development environment (IDE) called R Studio. Since the summer semester is only 1 month (10 classes), it is **critical to have your computer set up and ready to go before the first day of class**.

Throughout the course, there will be a set of pre-lecture activities and/or readings for you to complete. **These activities prepare you for the in-class activities**. Failure to complete them will put you behind in an already compressed course.

To prepare for the first class:

1.  Install R and R Studio
    -   [installation video tutorial](https://www.youtube.com/watch?v=eQFu_zzF96o)
    -   Detailed instructions on installing R and R Studio are available on [swirl](https://swirlstats.com/students.html).
        -   Complete step 1 and step 2

::: callout-tip

Swirl is a great tool to learn R interactively that we will use in the course. Feel free to explore more.
:::

2. In the first class, we will begin to get familiar with R. Complete the [Pre-reading material about R](./../readings/00-quarto/index.qmd). Pre-reading materials for each class are located under **Resources**. Sometimes, pre-reading materials are direct links to external resources for you to read in advance of the lecture.





# Lecture

## Acknowledgements

Material for this lecture was borrowed and adopted from

-   r4ds book: <https://r4ds.hadley.nz/quarto>
-   Quarto Publishing System: <https://quarto.org>

## Learning objectives

::: callout-note
### Learning objectives

**At the end of this lesson you will:**

-   Get an overview of the course (including staff, format, grading, etc)
-   Be able to recognize and operate an Integrated Developer Evironment (IDE) to perform statistial programming and data analysis.
-   Be able to describe reasons why having a personal website can be useful.
-   Recognize what is Quarto and how it's different from RMarkdown.
-   Be able to create a Quarto project and Quarto website.
:::
