---
title: "Building a Quarto Website and Using GitHub"
description: "Reading for Class 07"
author: 
  - name: Lindsay Hayes
    url: https://lindsaynhayes.github.io
    affiliation: Department of Cell Biology, OUHSC
date: 2025-07-28
draft: false
---

::: callout-note
### Learning objectives

**At the end of this lesson you will be able to:**

- Create a Github repository 
- Setup a Quarto Website
- Publish your Quarto website through Github Pages
- Customize your Quarto Website
:::

### Pre-class Tasks

Github is a web-based resource that allows you to save files online, track changes to files, and share project files easily for better collaboration. It has gained popularity in the scientific community as an easy way to document project scripts as reaserchers work through them, documenting changes or mistakes that may have been encountered in the process. 

Please create accounts with Github and Github Desktop before our next class time:

- [Set up a Github Account Online](https://docs.github.com/en/get-started/start-your-journey/creating-an-account-on-github)
- [Set up Github Desktop Account on your computer](https://docs.github.com/en/desktop/installing-and-authenticating-to-github-desktop/installing-github-desktop)
